In [2]:
import numpy as np

#activation function
def act(a):
    return a/(1+abs(a))
        
#derivative of activation function
def act_det(a):
    return 1/(1+abs(a))**2

def train(train_x,train_y,w,w0,neuronsnum,iternum,learning_rate):
    datalen=train_x.shape[0]
    cost=[]
    for i in range(iternum):
        neuronsnum
        z = act(np.dot(w,train_x)+w0)
        print(z)
        delta=z-train_y
        dw=np.dot(delta,z.T)/datalen
        dw0=np.sum(delta,axis=1,keepdims=True)/datalen
        da=np.dot(w.T,delta)
        w-=learning_rate*dw
        w0-=learning_rate*dw0
        error = np.dot((z-train_y).T,(z-train_y))/datalen
        #print(w)
        cost.append(error)
    return cost

In [3]:
train_data=np.loadtxt('sincTrain25.dt')
x_train=train_data[:,0]
y_train=train_data[:,1]
#test_data=np.loadtxt('sincValidate10.dt')
#x_test=test_data[:,0]
#y_test=test_data[:,1]

w1 = np.random.randn(1,x_train.shape[0])
print(w1)
b1 = np.zeros((1,x_train.shape[0]))
print(b1)
#x_train.shape[0] is sample amount
iternum=500
learning_rate=0.1

errlist = []
errlist=train(x_train,y_train,w1,b1,iternum=iternum,learning_rate=learning_rate)
#print(errlist)
#print(np.mean(errlist))

[[-0.37280262  1.31433475 -1.25644624  0.09840459 -1.3965775   1.65626185
  -0.56396646  0.04351241  1.57749807 -1.72569314 -0.34272002  0.85121964
   2.06573143  0.95431654 -0.68827443  0.90075379 -0.55834796 -0.24670595
   0.36740688 -1.90177443  0.46109007  0.66802884 -0.78833365  0.09030438
   0.33580411]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]


TypeError: train() missing 1 required positional argument: 'neuronsnum'

In [32]:
def h(x, deriv=False):
    if(deriv==True):
        return 1/(1+abs(x))**2
    return x/(1+abs(x))

####################################

def nn(x, y, w1, w2, flag):

    #Forward Propagation
    x0 = np.array([[1], [x]], float) #[1,xi]
    s1 = np.dot(w1.T, x0)
    x1 = np.vstack((np.array([[1]], float),h(s1)))
    s2 = np.dot(w2.T, x1)
    x2 = h(s2)

    if flag:
        return (x2 -y)**2

    d2 = 2 * (x2 - y) * h(s2, deriv=True)

    d1 = w2.dot(d2) * h(s1, deriv=True)

    w1 += x1.T.dot(d1) / 25.0
    w2 += x2.T.dot(d2) / 25.0
    
    return (w1, w2)

####################################

np.random.seed(1)

trainX = np.delete(train_data, 1, 1)
trainY = np.delete(train_data, 0, 1)

w1 = 2*np.random.rand(2, 1) - 1
w2 = 2*np.random.rand(2, 1) - 1

for (x, y) in train_data:
    (w1, w2) = nn(x, y, w1, w2, False)
    print("\n",w1,"\n",w2)

err = 0.0
for (x, y) in train_data:
    err += nn(x, y, w1, w2, True)
print(err/25.0)

[[1.     ]
 [5.94911]]

 [[-0.16520791]
 [ 0.44139707]] 
 [[-0.99585469]
 [-0.3914183 ]]
[[ 1.    ]
 [-1.0366]]

 [[-0.15584992]
 [ 0.45075506]] 
 [[-0.98250276]
 [-0.37806637]]
[[1.     ]
 [3.25678]]

 [[-0.15402519]
 [ 0.45257979]] 
 [[-0.97806267]
 [-0.37362627]]
[[1.     ]
 [7.82452]]

 [[-0.1533144 ]
 [ 0.45329058]] 
 [[-0.97202655]
 [-0.36759015]]
[[ 1.     ]
 [-3.60601]]

 [[-0.15238719]
 [ 0.45421779]] 
 [[-0.96787602]
 [-0.36343962]]
[[1.     ]
 [3.11564]]

 [[-0.15051714]
 [ 0.45608784]] 
 [[-0.96346495]
 [-0.35902856]]
[[ 1.     ]
 [-7.78696]]

 [[-0.14999334]
 [ 0.45661163]] 
 [[-0.9565749]
 [-0.3521385]]
[[ 1.     ]
 [-7.59809]]

 [[-0.14950236]
 [ 0.45710261]] 
 [[-0.9503412 ]
 [-0.34590481]]
[[1.     ]
 [2.08388]]

 [[-0.14361007]
 [ 0.46299491]] 
 [[-0.94123853]
 [-0.33680214]]
[[1.   ]
 [3.983]]

 [[-0.14260872]
 [ 0.46399626]] 
 [[-0.93784724]
 [-0.33341085]]
[[1.     ]
 [8.06012]]

 [[-0.14199729]
 [ 0.46460768]] 
 [[-0.93197004]
 [-0.32753364]]
[[1.     ]
 [7.87976]

In [8]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
np.delete(arr, 0, 0)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])